import type { Product, Category } from '../types';
type Seed = [
  string,
  Category,
  number,
  string,
  string,
  string,
  [number, number, number],
  string,
  string,
  string,
];
const seeds: Seed[] = [
  [
    'Cove lounge chair',
    'Seating',
    890,
    'Oak & linen',
    'A soft place to land.',
    'A rounded oak frame holds generous linen cushions, leaving a little daylight between the seat and arms. The low, gently reclined back makes room for a book, a conversation, or nothing in particular.',
    [76, 82, 74],
    'Oat linen / natural oak',
    '#c9bca4',
    'Moss linen / natural oak',
  ],
  [
    'Vale sofa',
    'Seating',
    2480,
    'Linen blend & oak',
    'Room for the everyday.',
    'Three deep seats, broad cushions and a low silhouette give Vale its easy presence. An open weave adds quiet texture, while the small oak feet keep the substantial form lightly lifted from the floor.',
    [228, 96, 72],
    'Oat linen',
    '#c8bba2',
    'Olive linen',
  ],
  [
    'Arc dining table',
    'Tables',
    1890,
    'Solid oak',
    'A generous curve, a natural gathering place.',
    'An oval oak top rests on two cylindrical timber pedestals. With no corners to navigate and an uninterrupted edge, Arc brings six people together without crowding a room.',
    [210, 100, 74],
    'Natural oak',
    '#b39468',
    'Smoked oak',
  ],
  [
    'Plinth side table',
    'Tables',
    420,
    'Travertine',
    'Stone, in its simplest form.',
    'A compact cylinder of pale travertine gives a glass, a lamp or a small stack of books a steady place to rest. Open pores and subtle mineral bands remain visible; each surface is represented as naturally varied.',
    [38, 38, 42],
    'Pale travertine',
    '#d3c5aa',
    'Warm limestone',
  ],
  [
    'Halo pendant',
    'Lighting',
    360,
    'Opal glass & brass',
    'A softer kind of centrepiece.',
    'A single opal globe filters light in every direction. Its slender brushed brass stem brings just enough definition above a dining table or beside a bed. Pair with a dimmable E26 LED bulb, supplied in this demo specification.',
    [30, 30, 60],
    'Brushed brass',
    '#bfa06c',
    'Brushed nickel',
  ],
  [
    'Reed floor lamp',
    'Lighting',
    480,
    'Brushed bronze',
    'Light that follows your evening.',
    'A slender stem meets a small adjustable cone, directing warm light over a shoulder and onto a page. A weighted circular base makes a small footprint feel settled. Demo specification: integrated 8W LED, 2700K.',
    [25, 32, 142],
    'Dark bronze',
    '#5a4835',
    'Brushed nickel',
  ],
  [
    'Line dining chair',
    'Seating',
    320,
    'Solid oak & linen',
    'A clear line around the table.',
    'A straight oak back and slim legs frame a small upholstered seat. Line is proportioned for dining, light enough to pull close and quiet enough to sit in a row.',
    [46, 49, 80],
    'Natural oak',
    '#b39468',
    'Smoked oak',
  ],
  [
    'Fold accent chair',
    'Seating',
    680,
    'Walnut & linen',
    'A sling with a little structure.',
    'A continuous linen sling folds through a walnut frame, balancing a relaxed seat with crisp joinery. Place it opposite a sofa or beside a low shelf where its open profile can be seen.',
    [68, 76, 76],
    'Walnut / flax',
    '#84664d',
    'Walnut / charcoal',
  ],
  [
    'Morrow bench',
    'Seating',
    620,
    'Solid oak',
    'A seat with room to spare.',
    'A long solid oak top rests on four square legs, keeping this bench simple and useful. Its narrow depth works at the end of a bed, along a dining table or in a generous entrance.',
    [150, 38, 44],
    'Natural oak',
    '#b39468',
    'Smoked oak',
  ],
  [
    'Low stool',
    'Seating',
    240,
    'Solid walnut',
    'An extra seat, close at hand.',
    'Three gently splayed legs support a thick circular walnut seat. The compact scale lets Low move between a living room, a bedside and the end of a table.',
    [34, 34, 43],
    'Natural walnut',
    '#7c5a41',
    'Dark walnut',
  ],
  [
    'Span coffee table',
    'Tables',
    740,
    'Solid walnut',
    'A broad, quiet surface.',
    'A low walnut slab with softly rounded corners rests on two broad supports. The wide grain and simple horizontal lines give books and everyday objects a considered foundation.',
    [120, 65, 32],
    'Natural walnut',
    '#7c5a41',
    'Dark walnut',
  ],
  [
    'Orbit side table',
    'Tables',
    290,
    'Solid oak',
    'Small enough to move with you.',
    'A round oak surface meets a central stem and cross foot. Pull Orbit alongside an armchair or leave it between two seats; its footprint leaves space for feet.',
    [45, 45, 48],
    'Natural oak',
    '#b39468',
    'Smoked oak',
  ],
  [
    'Beam console',
    'Tables',
    820,
    'Walnut veneer & solid walnut',
    'A long line for an entrance.',
    'A slim rectangular walnut top is supported by restrained timber legs. Beam gives a hallway space for a key bowl and a lamp without turning circulation into storage.',
    [140, 32, 78],
    'Natural walnut',
    '#7c5a41',
    'Dark walnut',
  ],
  [
    'Gather dining table',
    'Tables',
    1240,
    'Solid oak',
    'Everyone has a place in the circle.',
    'Three substantial oak legs hold a round top with an eased edge. Gather seats four comfortably and encourages conversation across a smaller dining space.',
    [120, 120, 74],
    'Natural oak',
    '#b39468',
    'Smoked oak',
  ],
  [
    'Dune table lamp',
    'Lighting',
    210,
    'Glazed ceramic',
    'Light with a rounded edge.',
    'A mushroom-shaped ceramic shade and stem form one quiet silhouette. A warm pool of light settles on the surface below. Demo specification: E14 LED, 5W, 2700K.',
    [28, 28, 36],
    'Chalk ceramic',
    '#e1d9c9',
    'Clay ceramic',
  ],
  [
    'Column table lamp',
    'Lighting',
    280,
    'Travertine & linen',
    'Texture, lit from within.',
    'A straight travertine base supports a woven linen shade. The stone brings weight and the fabric softens the light. Demo specification: E26 LED, up to 8W, bulb included.',
    [32, 32, 52],
    'Pale travertine',
    '#d3c5aa',
    'Warm limestone',
  ],
  [
    'Loop wall light',
    'Lighting',
    195,
    'Brushed metal & opal glass',
    'A point of light on the wall.',
    'An open metal loop holds an opal globe close to the wall. Use a pair around a mirror or one above a bedside. Demo specification: hardwired, E14 LED, 5W.',
    [20, 18, 30],
    'Brushed brass',
    '#bfa06c',
    'Brushed nickel',
  ],
  [
    'Tilt task lamp',
    'Lighting',
    230,
    'Steel & brass',
    'A useful angle.',
    'Two articulated sections position a focused desk light exactly where it is useful. A weighted base and small metal shade keep the visual footprint modest. Demo specification: integrated 6W LED, 3000K.',
    [18, 40, 50],
    'Black brass',
    '#39332b',
    'Brushed nickel',
  ],
  [
    'Grid sideboard',
    'Storage',
    1640,
    'Oak veneer & solid oak',
    'Give everyday things a home.',
    'Four flush doors bring a calm grid to a long oak cabinet. Adjustable shelves divide the interior for tableware, linens and the objects you prefer out of sight.',
    [180, 42, 72],
    'Natural oak',
    '#b39468',
    'Smoked oak',
  ],
  [
    'Frame shelf',
    'Storage',
    980,
    'Walnut veneer & solid walnut',
    'A place for the things you keep.',
    'Four open shelves sit between tall walnut uprights. The unbacked construction leaves the wall visible and gives books and useful objects a clear, adaptable frame.',
    [90, 32, 180],
    'Natural walnut',
    '#7c5a41',
    'Dark walnut',
  ],
  [
    'Nook cabinet',
    'Storage',
    760,
    'Oak veneer & solid oak',
    'Compact storage, considered proportions.',
    'Two oak doors enclose adjustable shelving in a compact cabinet. Nook fits a modest entrance or living room alcove, with enough top surface for a light and a bowl.',
    [80, 38, 86],
    'Natural oak',
    '#b39468',
    'Smoked oak',
  ],
  [
    'Vessel vase',
    'Objects',
    85,
    'Stoneware',
    'A form for a single stem.',
    'An irregular bone-coloured ceramic volume narrows to a generous opening. Its matte surface catches small changes in daylight. A glazed interior is designed to hold water.',
    [18, 18, 27],
    'Bone ceramic',
    '#ded5c4',
    'Clay ceramic',
  ],
  [
    'Ridge bowl',
    'Objects',
    95,
    'Solid walnut',
    'A low centre of gravity.',
    'A wide, shallow wood bowl gathers fruit or everyday objects into one place. Concentric grain is the only decoration on its gently carved surface.',
    [32, 32, 8],
    'Natural walnut',
    '#7c5a41',
    'Dark walnut',
  ],
  [
    'Thread wool throw',
    'Objects',
    160,
    'Wool',
    'An extra layer for slow evenings.',
    'A soft wool throw in an open, gently textured weave, finished with a short fringe. Fold it over an arm or keep it close for the change in temperature at dusk.',
    [130, 180, 1],
    'Oat wool',
    '#c8bba2',
    'Olive wool',
  ],
];
export const categories: Category[] = ['Seating', 'Tables', 'Lighting', 'Storage', 'Objects'];
export const seedProducts: Product[] = seeds.map((s, i) => {
  const [
    name,
    category,
    dollars,
    material,
    short,
    description,
    [width, depth, height],
    finish,
    color,
    second,
  ] = s;
  const slug = name.toLowerCase().replaceAll(' ', '-');
  const image = `/images/${slug}.webp`;
  const care =
    category === 'Lighting'
      ? 'Disconnect the power before cleaning. Use a soft, dry cloth on metal and glass. Installation of hardwired pieces requires a qualified electrician.'
      : material.includes('Travertine')
        ? 'Wipe spills promptly with a damp soft cloth. Avoid acidic cleaners, abrasive pads and prolonged standing water. Use a coaster under drinks.'
        : material.includes('linen') || material.includes('Linen') || material === 'Wool'
          ? 'Vacuum textiles gently with an upholstery attachment. Blot spills without rubbing. Professionally clean upholstery; dry-clean the wool throw. Wipe timber with a soft, slightly damp cloth.'
          : 'Dust with a soft cloth. Wipe spills promptly and avoid abrasive cleaners or prolonged direct heat. Protect timber from standing water; hand-wash ceramics gently.';
  return {
    id: `p-${String(i + 1).padStart(2, '0')}`,
    slug,
    name,
    category,
    short,
    description,
    material,
    dimensions: { width, depth, height },
    care,
    delivery:
      category === 'Objects' || category === 'Lighting'
        ? 'Dispatches in 3–5 demo business days'
        : 'Dispatches in 7–14 demo business days',
    images:
      i < 6 ? [image, `/images/${slug}-alternate.webp`, `/images/${slug}-detail.webp`] : [image],
    featured: i < 6,
    archived: false,
    variants: [
      {
        id: `v-${i + 1}-1`,
        sku: `FF-${String(i + 1).padStart(3, '0')}-01`,
        name: finish,
        finish,
        color,
        price: dollars * 100,
        stock: i === 20 ? 0 : i === 3 ? 3 : i === 16 ? 2 : 12 + (i % 5),
        image,
      },
      {
        id: `v-${i + 1}-2`,
        sku: `FF-${String(i + 1).padStart(3, '0')}-02`,
        name: second,
        finish: second,
        color:
          second.includes('Olive') || second.includes('Moss')
            ? '#72795c'
            : second.includes('nickel')
              ? '#a4a5a0'
              : second.includes('Clay')
                ? '#a1755c'
                : '#68503b',
        price: (dollars + Math.round((dollars * 0.08) / 5) * 5) * 100,
        stock: i % 4 === 0 ? 0 : 4 + (i % 3),
        image,
      },
    ],
    related: [],
  };
});
for (const p of seedProducts)
  p.related = seedProducts
    .filter((x) => x.id !== p.id && x.category === p.category)
    .slice(0, 4)
    .map((x) => x.slug);
export const collections = [
  {
    slug: 'considered-essentials',
    title: 'Considered essentials',
    description:
      'A few good pieces, with room for everything else. Start with the forms we return to most.',
    products: seedProducts.filter((p) => p.featured).map((p) => p.slug),
  },
  {
    slug: 'soft-geometry',
    title: 'Soft geometry',
    description: 'Rounded edges, sculptural silhouettes and a little space to breathe.',
    products: [
      'cove-lounge-chair',
      'arc-dining-table',
      'plinth-side-table',
      'halo-pendant',
      'gather-dining-table',
      'vessel-vase',
      'dune-table-lamp',
    ],
  },
  {
    slug: 'after-hours',
    title: 'After hours',
    description: 'A lower light, a deeper seat. Objects for the quieter part of the day.',
    products: [
      'reed-floor-lamp',
      'vale-sofa',
      'fold-accent-chair',
      'column-table-lamp',
      'thread-wool-throw',
      'span-coffee-table',
    ],
  },
];
